// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FilterCheckbox: typeof import('./components/VFilter/FilterCheckbox.vue')['default']
    FilterDate: typeof import('./components/VFilter/FilterDate.vue')['default']
    FilterInput: typeof import('./components/VFilter/FilterInput.vue')['default']
    FilterRadio: typeof import('./components/VFilter/FilterRadio.vue')['default']
    FilterSelect: typeof import('./components/VFilter/FilterSelect.vue')['default']
    FilterToggle: typeof import('./components/VFilter/FilterToggle.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableSet: typeof import('./components/TableSet.vue')['default']
    VFilter: typeof import('./components/VFilter/index.vue')['default']
    VHeader: typeof import('./components/VHeader.vue')['default']
    VUpload: typeof import('./components/VUpload.vue')['default']
  }
}

export {}
