// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    FilterCheckbox: typeof import('./components/VFilter/FilterCheckbox.vue')['default']
    FilterDate: typeof import('./components/VFilter/FilterDate.vue')['default']
    FilterInput: typeof import('./components/VFilter/FilterInput.vue')['default']
    FilterRadio: typeof import('./components/VFilter/FilterRadio.vue')['default']
    FilterSelect: typeof import('./components/VFilter/FilterSelect.vue')['default']
    FilterToggle: typeof import('./components/VFilter/FilterToggle.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableSet: typeof import('./components/TableSet.vue')['default']
    VFilter: typeof import('./components/VFilter/index.vue')['default']
    VHeader: typeof import('./components/VHeader.vue')['default']
    VUpload: typeof import('./components/VUpload.vue')['default']
  }
}

export {}
