name: build

on:
  push:
    branches:    
      - master
  
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - run: pnpm install

      - run: pnpm build
      - uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.ZMJS_ML }}
          ARGS: "-az --delete"
          FOLDER: "./dist/"
          SERVER_PORT: "22"
          SERVER_IP: "zmjs.ml"
          USERNAME: "root"
          SERVER_DESTINATION: "/tmp/wx"